FROM fedora:28
MAINTAINER Rene Cannao <rene.cannao@gmail.com>

RUN dnf install -y automake bzip2 cmake make gcc-c++ gcc git openssl openssl-devel patch tar wget rpm-build gnutls python2 gnutls-devel libtool libunwind libunwind-devel

