FROM debian:7.8
MAINTAINER Rene Cannao <rene.cannao@gmail.com>

RUN apt-get update && apt-get install -y\
    automake\
    cmake\
    equivs\
    make\
    g++\
    gcc\
    gdb\
    gdbserver\
    git\
    python\
    libmysqlclient-dev\
    libssl-dev\
    libtool\
    libboost1.49-all-dev
