FROM almalinux:9
MAINTAINER Miro Stauder <miro@sysown.com>

RUN yum -y update

# proxysql dependencies
RUN yum -y install\
	groff-base\
	ncurses\
	perl-Carp\
	perl-Data-Dumper\
	perl-Digest\
	perl-Digest-MD5\
	perl-Encode\
	perl-Errno\
	perl-Exporter\
	perl-File-Path\
	perl-File-Temp\
	perl-Getopt-Long\
	perl-HTTP-Tiny\
	perl-IO\
	perl-MIME-Base64\
	perl-Net-SSLeay\
	perl-PathTools\
	perl-Pod-Escapes\
	perl-Pod-Perldoc\
	perl-Pod-Simple\
	perl-Pod-Usage\
	perl-Scalar-List-Utils\
	perl-Socket\
	perl-Storable\
	perl-Term-ANSIColor\
	perl-Term-Cap\
	perl-Text-ParseWords\
	perl-Text-Tabs+Wrap\
	perl-Time-Local\
	perl-URI\
	perl-Unicode-Normalize\
	perl-constant\
	perl-interpreter\
	perl-libnet\
	perl-libs\
	perl-macros\
	perl-parent\
	perl-podlators\
	perl-threads\
	perl-threads-shared\
	ca-certificates
