FROM ubuntu:14.04
MAINTAINER Rene Cannao <rene.cannao@gmail.com>

RUN apt-get update && apt-get install -y\
    automake\
    cmake\
    equivs\
    make\
    g++\
    gcc\
    gdb\
    gdbserver\
    git\
    libmysqlclient-dev\
    libssl-dev\
    libtool
