FROM fedora:27
MAINTAINER Rene Cannao <rene.cannao@gmail.com>

RUN dnf install -y automake bzip2 cmake make gcc-c++ gcc git openssl openssl-devel patch python2 tar wget rpm-build gnutls gnutls-devel libtool libunwind libunwind-devel