FROM debian:10
MAINTAINER Rene Cannao <rene.cannao@gmail.com>

RUN apt-get update && apt-get install -y\
    automake\
    cmake\
    equivs\
    make\
    g++\
    gcc\
    gdb\
    gdbserver\
    git\
    python\
    libgnutls-dev\
    libmariadbclient-dev\
    libssl-dev\
    libtool\
    vim
