FROM centos:centos7
MAINTAINER Rene Cannao <rene.cannao@gmail.com>

RUN yum install -y automake
RUN yum install -y bzip2
RUN yum install -y cmake
RUN yum install -y make
RUN yum install -y gcc-c++
RUN yum install -y gcc
RUN yum install -y git
RUN yum install -y openssl
RUN yum install -y openssl-devel
RUN yum install -y patch
