FROM fedora:24
MAINTAINER Rene Cannao <rene.cannao@gmail.com>

RUN dnf install -y automake bzip2 cmake make gcc-c++ gcc git openssl openssl-devel patch tar wget rpm-build python2 gnutls gnutls-devel libtool libunwind libunwind-devel
