name: Dockerfile Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          failure-threshold: warning
